### ISSUE TITLE
「投票の作成」フォームでUser nameを空欄のまま「登録する」ボタンを押すと、登録フォームのみが表示される

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#13]

**Comment by ykominami** [comment]
app/controller/polls/votes_controller.rbにおいて、createメソッド中の@vote.saveで失敗(validateionエラー)失敗した場合も、成功時と同様にフォーマットに応じたrenderを行う必要がある。
また、成功時と同様に、app/views/polls/votes/new.turbo_stream.erbも必要になる。

**Comment by ykominami** [comment]
#12にたいして、turbo_stream.updateを用いて、リンクがturbo_frame_tagで囲まれている状態にすると、この現象は発生しないようです。

**Comment by ichiroc** [comment]
#17 で解決したのでクローズします！
