### ISSUE TITLE
投票更新フォームでUser nameを空欄にして「更新する」ボタンを押すと、投票更新フォームのみが表示される。

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#14]
app/controller/polls/votes_controller.rbにおいて、updateメソッド中の@vote.updateで失敗(validateionエラー)した場合も、成功時と同様にフォーマットに応じたrenderを行う必要がある。
また、成功時と同様に、app/views/polls/votes/edit.turbo_stream.erbも必要になる。

**Comment by ykominami** [comment]
#12にたいして、turbo_stream.updateを用いて、リンクがturbo_frame_tagで囲まれている状態にすると、この現象は発生しないようです。

**Comment by ichiroc** [comment]
#17 で解決したのでクローズします！
