### ISSUE TITLE
choice毎のstatusの小計を一度に取得するSQL文

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#18]
touhyousanでpoll_idが指定された場合に、choice毎のstatusの値の個数を取得する。
touhyousanの仕様から、必ず全てのchoiceについてstatusが設定されるので、choicesテーブルに対して、vote_detailsテーブルをinner joinして求めてみた。
ただし、3種類あるstatusの値すべてが設定されるとは限らないため、プログラム中で指定されていないstatusの値を確認する必要がある。
また、order by は人間がselect結果を見やすくするためのもので、プログラムでは必要ないと思う。

select vd.choice_id, vd.status, count(vd.choice_id) from choices as c inner join vote_details as vd on c.id = vd.choice_id where c.poll_id = 54  group by vd.choice_id, vd.status order by vd.choice_id, vd.status;
 choice_id | status | count
-----------+--------+-------
       161 |      0 |     2
       161 |      1 |     1
       161 |      2 |     4
       162 |      0 |     1
       162 |      1 |     1
       162 |      2 |     5
       163 |      0 |     2
       163 |      2 |     5

**Comment by ykominami** [comment]
これはバグ報告ではなく、改善の提案です。
Hotwire.love meetup Vol.8 の中で、現在の実装が効率的でないという話が出たので、SQL文を試しに書いてみたということです。

**Comment by ichiroc** [comment]
なるほどー、ありがとうございます！
これも良いのですが、生SQLじゃなくて ActiveRecord で取れると更に良さそうですね！

**Comment by ruzia** [comment]
特にその後のやりとりがないのと大分古い物ベースの話なので一旦クローズしておきますね
