### ISSUE TITLE
新規登録後もchoiceをCRUDできる＆参加者各自が登録できるようにしたい

### ISSUE THREAD

**Issue by JunichiIto** [hotwire-love/touhyosan#32]
イベント開催前に選択肢（Choices text）A、Bを登録しておいて、イベント開催中にC、Dを追加する、もしくはAの内容を一部修正する、みたいなことをできるようにしたい。

<img width="593" alt="Screenshot 2023-01-26 at 17 50 51" src="https://user-images.githubusercontent.com/1148320/214794201-89fa1168-2870-4399-a5eb-91dbeb51ba3b.png">

**Comment by JunichiIto** [comment]
投票後にchoiceが追加された場合の仕様も要検討。

**Comment by ykominami** [comment]
Hotwire.love meetup Vol.21(2023/9/14)で話したい話題とした、「選択肢を提案できる」機能のUI案をPULL REQUESTしようと思います。
このissueと対比すると、「登録」ではなく「提案」となっています。各自が登録できるようにする、あるいは新規登録後もCRUDできるというのは、UIとしても複雑になりそうに感じたので、まずは「提案」する（登録は一人の人が行う）という仕様を考えてみました。

**Comment by JunichiIto** [comment]
https://github.com/hotwire-love/touhyosan/pull/71#issuecomment-1729045582 にもコメントしましたが、まずはスクショを見せてもらって、それをベースに議論できるといいかなと思いました。（視覚的な情報がないと議論しづらいので）
