### ISSUE TITLE
vote/create, vote/updateのフラッシュメッセージが次にvote/create, vote/updateが実行されるまで表示され続けている

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#33]
現在のtouhyousanのフラッシュメッセージは、もともと意図していたものとは、異なる挙動になっていると思います。

turbo_driveを利用していた場合は、意図通りだと思うのですが、turbo_frame, turbo_streamで画面遷移をしない場合は、ずっと表示されっぱなしになっています。

また、さらに非同期にブロードキャストで変更されると、フラッシュメッセージが何を伝えるのか分からなくなると感じています。

**Comment by ykominami** [comment]
TurboDriveでの画面遷移のイメージ
[![This is an image](https://g.gravizo.com/svg?digraph%20G%20{%20%22/%22%20[shape=box];%20%22/polls/:poll_id%22%20[shape=box]%20%22/polls/:poll_id/votes/new%22%20[shape=box]%20%22/polls/:poll_id/votes/:id/edit%22%20[shape=box]%20%22(outer)%22%20[shape=oval]%20%22(outer)%22%20-%3E%20%22/%22%20[label%20=%20%221%22]%20%22(outer)%22%20-%3E%20%22/polls/:poll_id%22%20[label%20=%20%222%22]%20%22/%22%20-%3E%20%22/polls/:poll_id%22%20[label%20=%20%223%22]%20%22/polls/:poll_id%22%20-%3E%20%22/polls/:poll_id/votes/new%22%20[label%20=%20%224%22]%20%22/polls/:poll_id/votes/new%22%20-%3E%20%22/polls/:poll_id%22%20[label%20=%20%225%22]%20%22/polls/:poll_id%22%20-%3E%20%22/polls/:poll_id/votes/:id/edit%22[label%20=%20%226%22]%20%22/polls/:poll_id/votes/:id/edit%22%20-%3E%20%22/polls/:poll_id%22[label%20=%20%227%22]%20})
](https://g.gravizo.com/svg?%20digraph%20G%20{%20%22/%22%20[shape=box];%20%22/polls/:poll_id%22%20[shape=box]%20%22/polls/:poll_id/votes/new%22%20[shape=oval%20style=dashed]%20%22/polls/:poll_id/votes/:id/edit%22%20[shape=oval%20style=dashed]%20%22(outer)%22%20[shape=oval]%20%22(outer)%22%20-%3E%20%22/%22%20%22(outer)%22%20-%3E%20%22/polls/:poll_id%22%20%22/%22%20-%3E%20%22/polls/:poll_id%22%20subgraph%20cluster1%20{%20%22/polls/:poll_id%22%20-%3E%20%22/polls/:poll_id/votes/new%22%20[style=dotted]%20%22/polls/:poll_id/votes/new%22%20-%3E%20%22/polls/:poll_id%22%20[style=dotted]%20%22/polls/:poll_id%22%20-%3E%20%22/polls/:poll_id/votes/:id/edit%22%20[style=dotted]%20%22/polls/:poll_id/votes/:id/edit%22%20-%3E%20%22/polls/:poll_id%22%20[style=dotted]%20}%20})

turb_frame, turbo_streamでの画面の一部更新のイメージ(実践部分が一画面、はスン部分が画面の一部更新）
[![This is an image](https://g.gravizo.com/svg?%20digraph%20G%20{%20%22/%22%20[shape=box];%20%22/polls/:poll_id%22%20[shape=box]%20%22/polls/:poll_id/votes/new%22%20[shape=box%20style=dashed]%20%22/polls/:poll_id/votes/:id/edit%22%20[shape=box%20style=dashed]%20%22(outer)%22%20[shape=oval]%20%22(outer)%22%20-%3E%20%22/%22%20%22(outer)%22%20-%3E%20%22/polls/:poll_id%22%20%22/%22%20-%3E%20%22/polls/:poll_id%22%20subgraph%20cluster1%20{%20%22/polls/:poll_id%22%20-%3E%20%22/polls/:poll_id/votes/new%22%20[style=dotted]%20%22/polls/:poll_id/votes/new%22%20-%3E%20%22/polls/:poll_id%22%20[style=dotted]%20%22/polls/:poll_id%22%20-%3E%20%22/polls/:poll_id/votes/:id/edit%22%20[style=dotted]%20%22/polls/:poll_id/votes/:id/edit%22%20-%3E%20%22/polls/:poll_id%22%20[style=dotted]%20}%20})

**Comment by ruzia** [comment]
今のflash周りの実装は相当適当なので、トーストで出すようにするとか綺麗にしてみるとよさそうですねー

**Comment by JunichiIto** [comment]
https://github.com/hotwire-love/touhyosan/pull/68 で対応したのでこちらはクローズさせてもらいますね！
