### ISSUE TITLE
debug.cssの導入

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#39]
「猫でもわからHotwire入門 Turbo編」で紹介されていたのですが、以下のCSSを適用すると、turbo-frame領域に枠が表示されます。　
デバッグ時には有用化と思い提案します。

[debug\.css](https://gist.github.com/swanson/f6e5c927671116bef8ae1bea07d65b13)

**Comment by morikiyo** [comment]
https://zenn.dev/shita1112/books/cat-hotwire-turbo/viewer/turbo-frames#turbo-frame%E3%81%AE%E8%A6%8B%E3%81%88%E3%82%8B%E5%8C%96

この記事ですかね？
みんなに聞いた上で導入するかどうか決めますね。

**Comment by morikiyo** [comment]
前回導入できたのでクローズしますね。
