### ISSUE TITLE
ruby.wasmによるイベントハンドラの実装、ruby<->JavaScript間の通信、連携

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#40]

**Comment by ruzia** [comment]
https://github.com/hotwire-love/touhyosan/pull/50#issuecomment-1510603479

こちらのコメントでも書いたとおり、もしもStimulusと良い感じに連携させるといった形でHotwireに関係のある状態にできたら再度issueなどを上げてもらえるとうれしいです！

こちらもいったんクローズしてしまいますね
