### ISSUE TITLE
本番環境だとモーダルが閉じた後に新規投票フォームが立ち上がる

### ISSUE THREAD

**Issue by JunichiIto** [hotwire-love/touhyosan#43]
ローカルだと起きない。なぜ？？
https://touhyosan.hotwire.love/polls/1

**Comment by JunichiIto** [comment]
https://github.com/hotwire-love/touhyosan/pull/44 にて修正

**Comment by ykominami** [comment]
#44 修正前のコードに対してですが、ローカルでも発生した場合があるので、そのことを報告します。

commit (5dca7c0441c7ee88ea24b8f66c65f39e12561c6c) に対して、ローカルでいろいろ試したところ、ローカルでも2回、このissuedで報告されている現象が発生しました。
ただ1回発生しても、続けては発生しませんでした。
発生したのは、データベースを作り直し、rails db:prepare, rails db:seedをした後、最初に作成したpollに対して、最初のvoteでした。

また、私の環境では、bin/setupを実行すると、polls/1 はActiveRecord::RecordNotFoundになり、　polls2はNoMethodError in Polls#showになり、新規に作成した投票はpolls/3から始まります。

また、リポジトリでのconfig/database.ymlで指定されあ環境はdevelopment, testだけのようですが、本番環境にはproductionも追加されているのでしょうか。

**Comment by ykominami** [comment]
#44で提案されている方法で、不具合が発生する可能性は減ると思います。

Stimulusのmodalのコントローラのshowメソッドが呼び出されるか否かをconsole.logメソッドで表示させて確認したところ、#44 で提案されている修正をする前の状態では、ローカルの環境でも本番環境でも、どちらの場合でもshowメソッドは呼び出されていました。
モーダルが表示されるか、されないかは、showメソッドから呼び出される(bootstrapの)Modalインスタンスのshowメソッドで表示されるか、されないかに依存しているようです。

設計として、状態(表示するかしないか)とタイミング（表示する場合のタイミング）の両方を考慮する必要があると思います。

HotWireを用いない場合は、サーバ側で表示するかしないかを判断し、表示する場合はその内容も更新して、クライアントに送ります。

HotWireを用いる場合は、表示するかしないかを判断と、表示する場合はその内容の更新を、サーバ側で行うか、クライアント側で行うかを決めて、実装する必要があるのではないでしょうか。

現在の実装は、クライアント側で表示するタイミングを決めているが、表示するかしないかの判断をサーバ側でも、クライアント側でも行わず、表示されるかしないかは、bootsrapのModalインスタンスのshowメソッド、hideメソッドの実行結果に依存している、私は考えています。

**Comment by morikiyo** [comment]
不具合の解消はしているので一旦クローズします。
