### ISSUE TITLE
勉強会のモブプロの成果を直接このリポジトリのブランチに対してpushできないか

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#45]
現在、モブプロをする場合は、ドライバー役が、hotwire-love/touhyousanをフォークし、フォークしたリポジトリをローカルにクローンし、ローカルに対してコミットした後、勉強会終了後にフォーク先にプッシュし、そしてhotwire-love/touhyousanにプルリクエストすることになっています。
ただしこのやり方の場合、プルリクエストを送ってから、mainブランチにマージされるまでに時間がかかると、勉強会参加者が後日勉強会で行った内容を確認しようと思っても、なかなか確認することができません。
mainブランチにマージする際には、勉強会で行ったことそのままではなく、整理・修正したほうがいい場合もあると思います。
ただ勉強会で行ったことを確認したい場合には、（整理・修正されていなくて）そのままの状態であっても、すぐにみることができたほうが嬉しいと思います。

このため、各勉強会毎にhotwire-love/touhyousanにモブプロ用のブランチを切り(例:vol12)、そこに一旦モブプロ時のcommitをpushし、勉強会の終わりに、その回のモブプロ用のブランチから、mainブランチへのマージ用のブランチを切り(例：vol12_pr)、そのブランチに対するプルリクエストを送って、それをmainブランチにマージしてはどうでしょうか。
vol12_prは作業用のブランチですので、mainブランチにマージした後は削除してかまわないと思います。
逆にvol12のほうは、ある程度の期間は残しておいた方がいいと思います。

**Comment by JunichiIto** [comment]
issue投稿ありがとうございます。
この問題は運営でも認識していて、これを回避するためにmainブランチとは別にdevelopmentブランチを作って、これをデフォルトブランチに設定しています。
詳しくは本日のミートアップで共有しますね。

<img width="279" alt="Screenshot 2023-03-23 at 16 26 47" src="https://user-images.githubusercontent.com/1148320/227132985-fcfde279-d5aa-40b2-8545-56ab3ddfbfe4.png">

**Comment by morikiyo** [comment]
Vol. 12 で説明させてもらいました。
一旦 develop ブランチを fork してもらう運用でしばらく様子を見ますね。
