### ISSUE TITLE
Rails Mermaid ERD gemを用いて、DBのERD図を作成、表示させる

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#47]
[RailsのER図をMermaidで柔軟に生成できるGemを作りました](https://zenn.dev/koedame/articles/ac4815887325ef?redirected=1)
[GitHub \- koedame/rails\-mermaid\_erd: Generate Mermaid ERD from your Ruby on Rails application\.](https://github.com/koedame/rails-mermaid_erd)

Gemfileにgemを指定して、bundle install後、以下を実行すると、mermaid_erd/index.htmlが生成されます。
```
bundle exec rails mermaid_erd
```
HTMLファイル1個のみですが、JavaScript用いて、いろいろなパターンで表示できます

**Comment by ruzia** [comment]
情報ありがとうございますー
今はまだ規模も小さくschema.rbで十分だと思うので一旦クローズしておきますね
