### ISSUE TITLE
「投票を作成」ボタンを押した後のフォームにおいて、選択肢の順序を入れ替える毎、また「登録する」ボタンを押したときに、投票が作成される

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#58]
以下のcommitに対するバグ報告です。

d75e2cc

以下のルーティングが設定されているため、フォームでsubmitした場合、POST /polls/:poll\_id/votes  polls/votes#createが該当する。

| Prefix | Verb | URL | コントローラ#アクション |  
| --- | --- | --- | --- |  
| root | GET | /  | polls#new |  
| poll\_votes  | POST | /polls/:poll\_id/votes(.:format)  | polls/votes#create |  
| new\_poll\_vote  | GET | /polls/:poll\_id/votes/new(.:format)  | polls/votes#new |  
| edit\_poll\_vote | GET  | /polls/:poll\_id/votes/:id/edit(.:format) | polls/votes#edit |  
| poll\_vote  | PATCH  | /polls/:poll\_id/votes/:id(.:format)  | polls/votes#update |  
|  | PUT    | /polls/:poll\_id/votes/:id(.:format)  | polls/votes#update |  
| polls  | POST | /polls(.:format) | polls#create |  
| new\_poll  | GET  | /polls/new(.:format) | polls#new |  
| poll  | GET | /polls/:id(.:format) | polls#show |

選択肢の順番の入れ替えをフォーム上で行う場合、デフォルトのルーティングから外れることにつなばるので、以下の点を仕様として検討、決定しておく必要があるのではないでしょうか。

1.  UI
    1.  いつ登録するののか（「登録する」ボタンを押した時なのか）- ここで登録するというのは、単にサーバに送信するか否かではなく、サーバ上で投票を確定したものとして扱うか否かを指します。
        1.  newアクションの時に、デフォルト値でレコードを新規登録すると、「登録する」ボタンを押すと、直前の選択肢の順番入れ替えの場合と同一内容をサーバに送ることになる。
            1.  ただし、「登録する」ボタンがないと、選択肢の順番を入れ替えずにそのまま登録するということが出来なくなる。
            2.  また、デフォルト値でレコードを新規登録する場合、デフォルト値が選択肢のスコアに影響を与えないようにしなければならない（デフォルト値として0点を与える、デフォルト値の場合はスコアの計算に利用しないなど）
    2.  （キャンセル出来るのか）
        1.  「登録する」ボタンを押した時に登録される場合、「登録する」ボタンを押す前にフォームを閉じると、キャンセルと同等の効果がある。
        2.  newアクションの時に、デフォルト値でレコードを新規登録すると、単にフォームを閉じた場合に、レコードが削除されずに残ってしまう。
2.  ルーティング
    1.  既存のルーティングを利用するか
        1.  利用しないルーティングが出てきたらどうするか
    2.  独自のルーティングを設定するか
3.  アクション
    1.  既存のアクションの処理内容を変更するか
    2.  独自のアクションを作成するか

**Comment by morikiyo** [comment]
前回のモブプロ会で修正されたのでこちらはクローズしますね。
https://github.com/hotwire-love/touhyosan/pull/59
