### ISSUE TITLE
rake spec:systemを実行するにはbin/setup以外に、事前にPlayWrightのインストールが必要

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#65]
勉強会Vol.18で実装したSystem specを実行するためには、bin/setupの実行以外に、PlayWrightをインストールする必要がある.
しかし、README.mdにそれに関する記述がない。

**Comment by JunichiIto** [comment]
ご提案ありがとうございます！
ただ、 https://github.com/hotwire-love/touhyosan/pull/63 のPRは「Vol.18 で試した結果、いまのところ効果は見込めない」という理由でクローズしました。
よってREADMEの更新もしばらく必要ないです。

すいませんが、こちらのissueはクローズさせてもらいますね。
