### ISSUE TITLE
npmのバージョンにより、rails new --css=bootstrap がエラーになる場合がある

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#70]
直接touhyousanとは関係ないのですが、touhyousanで利用しているbootstrapをrails newで指定してRailsアプリケーションを新規作成しようとすると、最終的にnpmがエラーを返して失敗します。
具体的にはnpmに対して、package.jsonファイルのscriptsフィールドに以下の内容を追加する時にエラーになります。
```
npm pkg set scripts.watch:css="nodemon --watch ./app/assets/stylesheets/ --ext scss --exec "yarn build:css""
```
はnpmに対するコマンドのUSAGEエラーになります。
ここで、以下のようにシングルクォートで囲むとエラーにならなくなります。
```
--exec 'yarn build:css'
```

エラー発生を確認したのは、Windows 10のWSL2でdebianパッケージの場合です。
asdfでruby, nodeをバージョン管理しています。
Ruby(3.0.2, 3.1.2, 3.2.2),Rails(7.0.8, 7.0.2.3), node(14.17.0, 17.1.0, 18.12.1, 19.8.1)のどの組み合わせでもエラーが発生しました。

エラーが発生しなかったのは、Mac OS Montley 12,6.9 の場合でした。
こちらもasdfでRuby, Nodeをバージョン管理していました。
こちらはどの組み合わせでもエラーが発生しましませんでした。
ただしnpmのバージョンは6.14.18でした。

そこで、Windows 10, WSL2でもnpmのバージョン6.14.18をグローバルにインストールして実行すると、エラーが発生しなくなりました。

npmのバージョン6.14.18から最新版(10.1.0)のどこからエラーが発生するかは未確認です。
```
npm pkg set <key>=<value>
```
において、<value>を""で囲んだ時に、その中でさらに文字列を""で囲むことが、npmの新しいバージョンで認められなくなっているようです。具体的にどのバージョンから認められなくなったかまでは確認できていません。

**Comment by JunichiIto** [comment]
すいません、話を読む限り、Rails本体 or npmパッケージのissueかな？という気がしています。
hotwire.love のテーマからはちょっと逸れてしまうので、本件はいったんクローズさせてください。
