### ISSUE TITLE
is_29 | propose_choice_uiと同じ

### ISSUE THREAD

**Issue by ykominami** [hotwire-love/touhyosan#89]

**Comment by JunichiIto** [comment]
@ykominami 
すいません、空のissueがたくさん作成されていますが、このリポジトリはpublicなリポジトリなので、issueを投稿するなら他の人が見てもわかるようなissueを投稿していただきたいです。

正直、こうした空っぽのissueはissue一覧のノイズになってしまうので、こちらで内容がよくわからないと判断したissueは申し訳ありませんがクローズさせていただきます。
